### ISSUE TITLE
Time and Timezone

### ISSUE THREAD

**Issue by rosgr100** [Plueres/spicetify-extensions#3]
I think that time and timezone are not necessary information. It would be better if it will get cleared and removed.
Such as day also.

Thank you!

![image](https://github.com/Plueres/spicetify-extensions/assets/74199552/8ad6aad8-1e3e-4bb2-98de-29627d41a03d)

Nevermind somehow this changed.

**Comment by Plueres** [comment]
I was already wondering how this could happen, but it might not have converted the time correctly. Glad it's back

**Comment by UnusualGravy** [comment]
hello im experiencing this aswell..

**Comment by UnusualGravy** [comment]
> hello im experiencing this aswell..

oh nvm it fixes if you change the date format, though it is odd that it does that when you first install

**Comment by Plueres** [comment]
> > hello im experiencing this aswell..
> 
> oh nvm it fixes if you change the date format, though it is odd that it does that when you first install

I wasn't able to reproduce it, but I'll see if i can find it out why it is happening
